### ISSUE TITLE
update parsing of the HTML5 spec file

### ISSUE THREAD

**Issue by dmitris** [hailiang/html-query#3]
Currently the generator in https://github.com/hailiang/html-query/tree/master/gen panics not being able to find the list of attributes.  Likely the format of the HTML5 spec file has changed and the parse needs to be adapted.

```
$ go build && ./gen
panic: Cannot find List of attributes
```

Parsing of the continuous "work-in-progress" HTML file is rather fragile - is the data like attributes and elements list available in some more parsing-friendly format like JSON?

The URL http://www.whatwg.org/specs/web-apps/current-work/multipage/section-index.html in https://github.com/hailiang/html-query/blob/master/gen/spec.go#L18  now redirects to https://html.spec.whatwg.org/multipage/indices.html#index - should be updated as well.

**Comment by h12w** [comment]
I have updated the generator with the new URL and the generator works fine. Just leave a comment here if you find further issues.

Also please tell me if you can find an official structured format of the data table in HTML spec.
