### ISSUE TITLE
I am unable to understand how do I access my DOM

### ISSUE THREAD

**Issue by amankapoor** [hailiang/html-query#5]
Hi, this is my DOM which I am trying to access:
```
<body>
    <table cellspacing="1" cellpadding="1" align="center" border="0" bgcolor="#999999">
        <tr bgcolor='#eee'>
            <td class="tdrow" align="center">
                <li>
                    <a href=somelink target="_blank">Some Text</a>
                </li>
            </td>
...
...
...
```
I want to reach to the `href` link and the text there, but I am unable to understand how to accomplish this through your library. I can do the same with goquery but I wanted to try your library since you have decoupled every element and it looks nice to me. But, I need more examples and help. The example which you gave was a div with a class, but many times there are no classes or ids, like my `table` above, so in this case, I was trying to find some nil checker to put inside `root.Td(some nil here)`, but I have no idea. Please guide.

**Comment by h12w** [comment]
The constraint expression can be omitted like this ```root.Table()```, as long as the table is unique (or the first one) within the context.
